name = "rosa-smp"
author = "musicalskele"
version = "0.0.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4c45ae395f8e24e03034f370e13bc8b7a6cd98e564a4b1e761d69c64ff60181"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
