name = "rosa-smp"
author = "musicalskele"
version = "0.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3708e4a760fa58b3e65393c16f578f969d486aee401cc03e0eba0b3ea404d989"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
