name = "rosa-smp"
author = "musicalskele"
version = "0.0.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e9982b458f7216d91f529560f2b2f8c283fa1b3fd01735f6dc891d8b04ac809"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
