name = "rosa-smp"
author = "musicalskele"
version = "0.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbeeafc9863aa52c60d769d2d28b24ea4eac8e17f03d9b4bef40c3f49a31e58e"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
