name = "rosa-smp"
author = "musicalskele"
version = "0.0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49e0757c6221269eac3a2cb372fa0711c70bc444167be28667b2c72bf781995b"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
