name = "rosa-smp"
author = "musicalskele"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5a1d816d9c6299c057f7cfc33eb1fda42d5609147c5df8e8cb6f67f5a710ede"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
