name = "rosa-smp"
author = "musicalskele"
version = "0.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9feae74da12c4600a434b670d0908beb7ca5bcbdfc32623abfa4cf17b90db5fe"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
