name = "rosa-smp"
author = "musicalskele"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "643e71ff8cb5330b1aa938bcb6ca6fc48d719752dad08f537d950ed16de63fd7"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
